### ISSUE TITLE
Error running the program

### ISSUE THREAD

**Issue by ganesshkumar** [izzatalasadi/Crypto_analysis#2]
I was able to install dependencies and run the command `streamlit run main.py`. How ever when the navigate to the URL I get the following error message getting displayed on the screen.

![image](https://user-images.githubusercontent.com/2135089/116837218-156a1180-abe7-11eb-9256-cb96933a67aa.png)

**Comment by izzatalasadi** [comment]
1-you have to generate a new marketcap api key from this link
https://coinmarketcap.com/api/
2-then you have to signup for free to get the api key
![image](https://user-images.githubusercontent.com/17545900/116851150-31bf7b80-abf2-11eb-939b-c382451dcc03.png)
3- copy the key and past it in the code (follow steps in readme)

**Comment by izzatalasadi** [comment]
i did fix the problem. hope the program helps u.

**Comment by ganesshkumar** [comment]
I have created a new key and pasted it in the main.py file but still facing the same error. 

My python and pip versions are as below
![image](https://user-images.githubusercontent.com/2135089/116899858-b55e8400-ac55-11eb-9d05-5beb95314865.png)

**Comment by ganesshkumar** [comment]
What version of python and pip do you use to run this program?

**Comment by ganesshkumar** [comment]
Pulled the latest changes. It's working fine now :)

**Comment by izzatalasadi** [comment]
that's good. looking forward to hear from you if there is anything i can do more to make the program more eff.

**Comment by ganesshkumar** [comment]
I am glad to find this. I am all good now. If there is any scope to make it more eff, we will discuss! I can help with coding as well :)
